INSERT INTO commoninfotype (commoninfotypecode)
VALUES ('HEADER'),
       ('ABOUTUS'),
       ('RATESCALE'),
       ('CONTACTS'),
       ('FAQ'),
       ('SOLUTIONS'),
       ('CERTIFICATE'),
       ('FORUM'),
       ('FORUMQUESTIONS'),
       ('FORUMSINGLEQUSTION'),
       ('FORUMASKAQUESTION'),
       ('QUICKCHECK'),
       ('QUICKCHECKAUDIO'),
       ('QUICKCHECKRULES'),
       ('QUICKCHECKTEST'),
       ('QUICKCHECKFORM'),
       ('EXAM'),
       ('QUICKCHECKLOADING');




INSERT INTO commoninfo (commoninfocode, commoninfotypeid)
VALUES ('headerMenuTitle',1),
       ('headerEducation',1),
       ('headerTests',1),
       ('headerSignIn',1),
       ('headerSignUp',1),
       ('headerAboutUs',1),
       ('headerContacts',1),
       ('headerForum',1),
       ('headerRatingScale',1),
       ('headerCertificate',1),
       ('headerSolution',1),
       ('headerExamen',1),
       ('headerHelp',1),
       ('headerTechQuestions',1),
       ('aboutMain',2),
       ('aboutAboutUsBreadcrumbs',2),
       ('aboutMission',2),
       ('aboutOurMission (нужен label и value)',2),
       ('aboutNITS',2),
       ('ratescaleRateScale',3),
       ('ratescaleTitle',3),
       ('ratescaleOverview',3),
       ('ratescaleAboutTest  (нужен label и value)',3),
       ('ratescaleA1 (нужен label и value)',3),
       ('ratescaleA2 (нужен label и value)',3),
       ('ratescaleB1 (нужен label и value)',3),
       ('ratescaleB2 (нужen label и value)',3),
       ('ratescaleC1 (нужен label и value)',3),
       ('ratescaleC2 (нужен label и value)',3),
       ('ratescaleScaleTitle',3),
       ('contactsContactUs (нужен label и value)',4),
       ('contactsName',4),
       ('contactsSecondName',4),
       ('contactsEmail',4),
       ('contactsPhone',4),
       ('contactsMessage',4),
       ('contactsSend',4),
       ('faqTitle',5),
       ('solutionsTitle',6),
       ('solutionsAdvantagesDescription',6),
       ('solutionsOneAdvantage1',6),
       ('solutionsOneAdvantage2',6),
       ('solutionsOneAdvantage3',6),
       ('solutionsOneAdvantage4',6),
       ('solutionsStep1Title',6),
       ('solutionsStep1',6),
       ('solutionsStep2Title',6),
       ('solutionsStep2',6),
       ('solutionsStep3Title',6),
       ('solutionsStep3',6),
       ('certificateCertificationBreadcrumb',7),
       ('certificateDilBannerDesc (label и content)',7),
       ('certificateDilBannerButton',7),
       ('certificateContentList1 (label и details)',7),
       ('certificateContentList2 (label и content)',7),
       ('forumBreadcrumb',8),
       ('forumAllTheme (label и content)',8),
       ('forumSidebarSearchTitle',8),
       ('forumSidebarSearchPlaceholder',8),
       ('forumSidebarThemeTitle',8),
       ('forumSidebarPopularTitle',8),
       ('forumSidebarPopularMoreBtn',8),
       ('forumTabsAllTheme',8),
       ('forumTabsFavorite',8),
       ('forumTabsMyQuestions',8),
       ('forumTabsNew',8),
       ('forumTabsPopular',8),
       ('forumRowTheme',8),
       ('forumRowAnswers',8),
       ('forumQuestionsQuestionDescr',9),
       ('forumQuestionsQuestionBtn',9),
       ('forumQuestionsTabsDiscussions',9),
       ('forumQuestionsTabsFavorite',9),
       ('forumQuestionsTabsMyQustions',9),
       ('forumQuestionsTabsNew',9),
       ('forumQuestionsTabsPopular',9),
       ('forumQuestionsRowViews',9),
       ('forumQuestionsRowAnswers',9),
       ('forumSingleQuestionShare',10),
       ('forumSingleQuestionAskQuestionBtn',10),
       ('forumSingleQuestionAnswerBtn',10),
       ('forumSingleQuestionAnswerUser',10),
       ('forumSingleQuestionAddMediaBtn',10),
       ('forumSingleQuestionCancelBtn',10),
       ('forumSingleQuestionCollapseBtn',10),
       ('forumAskQuestionBreadcrumb',11),
       ('forumAskQuestionTitle',11),
       ('forumAskQuestionFormTheme',11),
       ('forumAskQuestionFormTitle',11),
       ('forumAskQuestionFormWriteQuestion',11),
       ('forumAskQuestionFormBtn',11),
       ('quickCheckBreadcrumbs',12),
       ('quickCheckTitle',12),
       ('quickCheckBlockDescription (label и details)',12),
       ('quickCheckStartTestBtn',12),
       ('quickCheckWhyToPassTitle',12),
       ('quickCheckWhyToPass1 (label и content)',12),
       ('quickCheckWhyToPass2 (label и content)',12),
       ('quickCheckWhyToPass3 (label и content)',12),
       ('quickCheckStartLearnBlock (label и content)',12),
       ('quickCheckStartLearnBtn',12),
       ('quickCheckAudioTitle (label и content)',13),
       ('quickCheckAudioPlayBtn',13),
       ('quickCheckAudioNotHearingBtn',13),
       ('quickCheckAudioContinueBtn',13),
       ('quickCheckAudioNotHearingContent (label и details)',13),
       ('quickCheckRulesTitle (label и content)',14),
       ('quickCheckReadingBlock (label и details)',14),
       ('quickCheckAudioBlock (label и details)',14),
       ('quickCheckStartTestBtn',14),
       ('quickCheckTestLeftTableTitle',15),
       ('quickCheckTestLeftTableReading',15),
       ('quickCheckTestLeftTableAudio',15),
       ('quickCheckTestAudioBtn',15),
       ('quickCheckTestPreviousBtn',15),
       ('quickCheckTestNextBtn',15),
       ('quickCheckTestSkipBtn',15),
       ('quickCheckFormTitle (label и content)',16),
       ('quickCheckFormName',16),
       ('quickCheckFormSurname',16),
       ('quickCheckFormEmail',16),
       ('quickCheckFormBirthdate',16),
       ('quickCheckFormCountry',16),
       ('quickCheckFormCity',16),
       ('quickCheckFormGender',16),
       ('quickCheckFormCheckbox',16),
       ('quickCheckFormBtn',16),
       ('examFastTestBreadcrumbs',17),
       ('examTitle (label и content)',17),
       ('examBlockDescription (label и details)',17),
       ('examEnrollBtn',17),
       ('examWhyToPassTitle',17),
       ('examWhyToPass1 (label и content)',17),
       ('examWhyToPass2 (label и content)',17),
       ('examWhyToPass3 (label и content)',17),
       ('examStartLearnBlock (label и content)',17),
       ('quickCheckLoadingTitle (label и content)',18);

